<h2>1974</h2>
<p>Für uns Oldenburger und besonders auch für OM’s im Emsland war das Abschalten der Relaisstelle Lingen DB0UG Anfang 1974 ein großer Verlust. Das Relais befand sich auf der Burg in Bentheim mit etwa 120m Antennenhöhe und wurde von DJ8RI betrieben. Jedoch der adlige Einspruch des Burgherrn sorgte für ein jähes Ende des Betriebes dort. Aber dann kam im Dezember ein ganz vorzüglich funktionierendes Relais Meppen, DB0SM, auf R5 dazu. Auch wurde zusätzlich das Relais DB0VQ (R7) auf der Jugendherberge in Bentheim in Betrieb genommen. Damit war dieser Bereich im Emsland wieder hinreichend versorgt. DB0SM war etwa 15 km nördlich von Meppen. In der cqDL findet man DB0UG in der Liste vom 14.3.1972 verzeichnet, DB0SM und DB0VQ erst am 25.6.1975. Man kann davon ausgehen, daß die Relais da schon 6 Monate in Betrieb waren. Ich danke Eberhard, DJ8RI für diese Informationen.</p>
<p>Und jetzt wieder zum Wasserturm in Oldenburg.</p>
<!-- BILDER müssen hier noch rein -->
<div class="grid3">
    <p id="imgcaption"><img src="img/1974_bild01.jpg" id="grid_img">Vier Aufnahmen aus dem Turm, 1974, Manfred hatte mich bei Wartungsarbeiten mitgenommen. Hier der Blick nach Nordosten in die Huntewiesen. Die Autobahnbrücke ist noch nicht da. Und unten steht mein weißer VW Variant 1500 an der rechten Straßenseite.</p>
    <p id="imgcaption"><img src="img/1974_bild02.jpg" id="grid_img">Hier der Blick nach Südosten. Im Vordergrund die Nibelungenstraße, die Wehdestraße, und im Hintergrund der neue Silo am Stau und der Wasserturm der Klappbrücke. </p>
    <p id="imgcaption"><img src="img/1974_bild03.jpg" id="grid_img">Hier ein Photo nach Südwesten gegen die Sonne. In der Mitte die Graf Spee Straße, die sich auf den Wasserturm zuschlängelt, ganz vorne die Adelheidstraße. </p>
    <p id="imgcaption"><img src="img/1974_bild04.jpg" id="grid_img">Und hier eine Aufnahme nach Süden. Im wesentlichen die Donnerschweerstraße mit der Meisterschule. </p>
</div>
<p>Dann waren eine Zeitlang von Juni 1975 bis September zwei Relais zeitweise in Betrieb. Einmal DB0UO vom Wasserturm auf R2, 145,750, und probeweise DB0UO auf I3, 145,675, das neue Relais. Manfred betrieb es am Brookweg, bei sich zuhause. Das war schon komisch. In Friesoythe war ich mobil und konnte zwei Relaisstellen ansprechen. Man merkte aber sofort, das neue Relais hatte weniger Hub. 5 kHZ.</p>