<h2>2006</h2>

<p></p>
<section class="section_important" style="background-color: #CC0000;">
    <div style="display: block; font-weight: bold;">Manfred, DJ 6 UA, im Januar 2006 überraschend gestorben </div>
    Gerade bekam ich die Information, daß Manfred gestorben ist. Er hatte sich 34 Jahre um das Relais DB0UO und 21 Jahre um das Relais DB0OO gekümmert. Es war sein Lebenswerk. Wir werden ihn nicht vergessen. Die Relaisstellen bestimmten seine gesamte Freizeit.
</section>

<h3><p>Neue Informationen</p></h3>
<p>Leider habe ich vom Relaisverantwortlichen Klaus eben erfahren, daß voraussichtlich wegen der neuen Bestimmungen der Funkturmgesellschaft das Relais DB0UO seinen Betrieb nicht auf dem Standort Oldenburg Wahnbek fortsetzen wird, da die aufgenommene Leistung über der jetzt erlaubten liegt. Ferner ist die 2m Antenne zu groß. Das 70 cm Relais DB0OO wird möglicherweise nach einem Umbau am Standort verbleiben können, wenn es gelingt, die Eingangsleistung auf 100 Watt zu drosseln. Inzwischen arbeitet ja auch DB0WO in Leer wieder auf dem Wasserturm dort, es gab jedoch vor Jahren schon Hinweise, daß das Oldenburger 2m Relais nicht auf den Oldenburger Wasserturm zurückkommen kann, weil der ja nun ein Baudenkmal ist. Sobald ich neue Informationen habe, werde ich sie hier mitteilen. Leider ist wohl die schöne Zeit vorüber mit DB 0 UO in Wahnbek mit der Horizontalantenne. Höhepunkte gab es viele. Verbindung in die Ukraine und sehr häufig Stationen aus England, Schottland und Norwegen, Schweden und sehr oft Dänemark. Auch Stationen aus der Eiffel und Süddeutschland waren im Laufe der Betriebszeit in Wahnbek auf DB 0 UO oft zu hören. Und die vielen Jahre yl Runde klappten eigentlich wegen der Horizontalantenne so gut. Was macht der DARC? – Wird von dort Unterstützung kommen? Ich bezweifle es und hoffe doch. </p>
<h3><p>Oldenburger 2-m-Relais DB0UO qrt</p></h3>
<p>Die Forderungen der Deutschen Funkturm GmbH (DFMG) haben nun auch Auswirkungen auf die Oldenburger Relaisfunkstellen. Wie Klaus, DL8BDU, mitteilt, mußte das 2-m-Relais DB0UO vom Netz genommen werden. Eine Wiederinbetriebnahme ist zum jetzigen Zeitpunkt unwahr- scheinlich, da die Vorgaben mit dem vorhandenen Equipment nicht eingehalten werden kön- nen. Damit nimmt eine über 25jährige Ära des DX-UKW-Relaisfunks im 2-m-Band im nordwest deutschen Raum ein jähes Ende. Auch die Antennen des 70-cm-Relais am gleichen Standort müssen bis Ende April demontiert werden; hier ist aber eventuell eine Wiederinbetriebnahme des Relais nach entsprechenden Umbaumaßnahmen möglich. Rainer Victoria, DL5BG, Information Distrikt Nordsee.</p>